from flask.config import Config
from typing import Tuple

def parse_version(v: str) -> Tuple[int, int, int]: ...
def sqlalchemy_version(op: str, val: str) -> bool: ...
def engine_config_warning(
    config: Config, version: str, deprecated_config_key: str, engine_option: str
) -> None: ...
